"""
Mock LLM：开发/测试时返回固定文本，不调用真实 API
"""
from .base import BaseLLMService

MOCK_CAREPLAN_TEXT = """=== Care Plan (Mock) ===

1. Problem list / Drug therapy problems
- [Mock] Medication adherence monitoring needed
- [Mock] Drug interaction review recommended

2. Goals (SMART goals)
- [Mock] Patient will achieve therapeutic target within 12 weeks
- [Mock] Medication adherence >80%

3. Pharmacist interventions
- [Mock] Patient education on medication administration
- [Mock] Coordinate with prescribing provider

4. Monitoring plan
- [Mock] Lab schedule: CBC, metabolic panel every 4 weeks
- [Mock] Clinical follow-up in 4 weeks

--- Generated by mock LLM (USE_MOCK_LLM=1) ---"""


class MockLLMService(BaseLLMService):
    """Mock：直接返回固定文本"""

    provider_id = "mock"

    def generate(
        self,
        system_message: str,
        user_message: str,
        *,
        temperature: float = 0.7,
        max_tokens: int = 2000,
    ) -> str:
        return MOCK_CAREPLAN_TEXT
