"""
generate_careplan Lambda: 由 SQS 触发，读取 careplan_id，调用 Mock LLM，更新 RDS
"""
import json
import os
import ssl
import pg8000

DB_CONFIG = {
    "host": os.environ["DB_HOST"],
    "port": int(os.environ["DB_PORT"]),
    "database": os.environ["DB_NAME"],
    "user": os.environ["DB_USER"],
    "password": os.environ["DB_PASSWORD"],
    "ssl_context": ssl.create_default_context(),
}

MOCK_CONTENT = """=== Care Plan (Mock) ===

1. Problem list / Drug therapy problems
- [Mock] Medication adherence monitoring needed
- [Mock] Drug interaction review recommended

2. Goals (SMART goals)
- [Mock] Patient will achieve therapeutic target within 12 weeks
- [Mock] Medication adherence >80%

3. Pharmacist interventions
- [Mock] Patient education on medication administration
- [Mock] Coordinate with prescribing provider

4. Monitoring plan
- [Mock] Lab schedule: CBC, metabolic panel every 4 weeks
- [Mock] Clinical follow-up in 4 weeks

--- Generated by Lambda mock ---"""


def get_conn():
    return pg8000.connect(**DB_CONFIG)


def handler(event, context):
    for record in event.get("Records", []):
        try:
            body = json.loads(record["body"])
            careplan_id = body.get("careplan_id")
            if not careplan_id:
                continue

            conn = get_conn()
            try:
                cur = conn.cursor()
                cur.execute(
                    "UPDATE careplan_careplan SET status = 'processing' WHERE id = %s AND status = 'pending'",
                    (careplan_id,),
                )
                if cur.rowcount == 0:
                    conn.close()
                    continue

                cur.execute(
                    "UPDATE careplan_careplan SET status = 'completed', generated_content = %s WHERE id = %s",
                    (MOCK_CONTENT, careplan_id),
                )
                conn.commit()
            finally:
                conn.close()
        except Exception:
            raise  # Let SQS retry, then DLQ after 3 failures
    return {"statusCode": 200}
